export const FETCH_RECORDS = 'FETCH_RECORDS'

export const MORE_RECORDS = 'MORE_RECORDS'

export const ADD_COMMENT = 'ADD_COMMENT'

export const DELETE_COMMENT = 'DELETE_COMMENT'

export const DELETE_RECORD = 'DELETE_RECORD'

export const LIKE_RECORD = 'LIKE_RECORD'

export const UNLIKE_RECORD = 'UNLIKE_RECORD'

export const FILTER_RECORDS = 'FILTER_RECORDS'
